apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: node-tracer
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
    - image: gcr.io/amish-paradise/stackdriver-tracing-nodejs
  googleCloudBuild: {}
deploy:
  kubectl: {}
